### PR TITLE
allow dev.conf to be missing

### PR DESCRIPTION
**Pull request by bigloser**

### CODE REVIEW

**Comment by bigloser** [comment]
#review @jakeyr

**Comment by jakeyr** [comment]
Might it be better to handle this one level up (where dev.conf is loaded) vs. putting in a special-case handler at this level? Maybe not, not sure how play uses this function.

Let me know what you think.

**Comment by bigloser** [comment]
Maybe, but that function is private and therefore only used in the Play class. It seems putting it one level up would increase the surface area of this hack, while keeping it here would keep it limited.

**Comment by bigloser** [comment]
@jakeyr what do you think of this PR? It would allow us to get rid of individual dev confs in application.conf

Thank you!

**Comment by jakeyr** [comment]
Not sure I see why this would increase surface area. Seems `Play.java:436` is the right place to handle this exception. In fact, I'm curious why it isn't already being caught by the generic exception handling block in that location (is it a RuntimeException?)

**Comment by jakeyr** [comment]
Oh I see, because it would require removing the `fatalServerException()` inside. 

That still feels like the right thing to actually do here.

**Comment by jakeyr** [comment]
Also:

> It would allow us to get rid of individual dev confs in application.conf

I don't follow this. You just mean it would allow us to get rid of the checked in `dev.conf`?

**Comment by bigloser** [comment]
> I don't follow this. You just mean it would allow us to get rid of the checked in dev.conf?

So in prod, if dev.conf is missing it fails to start play. By making it a warning we can make dev.conf ignored in .gitignore and devs can place their configs in there instead of application.conf.

**Comment by bigloser** [comment]
> Not sure I see why this would increase surface area. Seems Play.java:436 is the right place to handle this exception. In fact, I'm curious why it isn't already being caught by the generic exception handling block in that location (is it a RuntimeException?)

Ah I see what you mean, I thought you meant in IO and not in Play. Yeah I think that is better let me try it out.

**Comment by bigloser** [comment]
Hmm, I still not sure I follow exactly what you are suggesting, I don't think we can modify the code near Play.java:436 since there is a System.exit in fatalServerException, we need to prevent that from being called in the first place.

Or are you suggesting to just remove the call to fatalServerException when _any_ include file is not found (and not special case it for dev.conf)?

**Comment by bigloser** [comment]
Alright @jakeyr I've removed the fatalServerException and let the code near Play.java:436 handle it (which just logs exceptions)

**Comment by jakeyr** [comment]
Ok, but it still needs to be handled at [`Play.java:348`](https://github.com/bigloser/play1/blob/37955e5a404a788545eb0fa46dba57049e10c48b/framework/src/play/Play.java#L348).

**Comment by bigloser** [comment]
@jakeyr why? won't any exception bubble up to the init method and caught there? Or are you saying we should just catch anything at Play.java:348 and handle it explicitly at that point?

**Comment by bigloser** [comment]
alright how about now @jakeyr ? it will exit if application.conf is not found.

**Comment by jakeyr** [comment]
:heart: 

#complete

Will kick off a play build of this for you once we vet out forest's new build so I can smoosh em together.

**Pull request merged**
